#!/usr/bin/env bash
# qa-audit.sh — hourly automated QA audit of the Claws dashboard
#
# Runs a lightweight gstack browse-based check of the dashboard at localhost:4318.
# - Checks if gateway + dashboard are reachable
# - Takes a screenshot
# - Reads console errors
# - Writes a timestamped report to ~/.claws/qa-audit/
#
# Designed for cron. Non-interactive, no-op if services not running.

set -euo pipefail

CLAWS_HOME="${CLAWS_HOME:-$HOME/.claws}"
AUDIT_DIR="$CLAWS_HOME/qa-audit"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT="$AUDIT_DIR/audit-$TIMESTAMP.md"
BROWSE="$HOME/.claude/skills/gstack/browse/dist/browse"
GATEWAY_URL="${CLAWS_GATEWAY_URL:-http://localhost:4317}"
DASHBOARD_URL="${CLAWS_DASHBOARD_URL:-http://localhost:4318}"

mkdir -p "$AUDIT_DIR"

{
  echo "# Claws QA Audit — $TIMESTAMP"
  echo
  echo "Generated by scripts/qa-audit.sh"
  echo

  # 1. Gateway health
  echo "## Gateway"
  if curl -sf -m 5 "$GATEWAY_URL/api/status" > /dev/null 2>&1; then
    STATUS=$(curl -sf -m 5 "$GATEWAY_URL/api/status" 2>/dev/null | head -c 500)
    echo "- ✅ Reachable at $GATEWAY_URL"
    echo "- Status preview: \`${STATUS:0:120}...\`"
  else
    echo "- ❌ NOT reachable at $GATEWAY_URL"
    echo "- Skipping dashboard check (gateway required)"
    echo
    echo "## Verdict"
    echo "- Gateway offline. No audit possible."
    exit 0
  fi
  echo

  # 2. Dashboard health
  echo "## Dashboard"
  if curl -sf -m 5 "$DASHBOARD_URL" > /dev/null 2>&1; then
    echo "- ✅ Reachable at $DASHBOARD_URL"
  else
    echo "- ❌ NOT reachable at $DASHBOARD_URL"
    echo
    echo "## Verdict"
    echo "- Dashboard offline."
    exit 0
  fi
  echo

  # 3. Browse binary check
  if [ ! -x "$BROWSE" ]; then
    echo "## Browse"
    echo "- ⚠ gstack browse binary not available at $BROWSE"
    echo "- Skipping visual audit"
    echo
    echo "## Verdict"
    echo "- HTTP checks passed. Run gstack setup to enable visual audits."
    exit 0
  fi

  # 4. Visual audit via gstack browse — capture all live surfaces
  echo "## Visual audit"

  capture_surface() {
    local label="$1"
    local url="$2"
    local final_shot="$AUDIT_DIR/${label}-$TIMESTAMP.png"
    # The browse binary is sandboxed to /private/tmp + the repo path. Write to /tmp
    # then move to the final audit dir.
    local tmp_shot="/tmp/claws-qa-${label}-$$-$RANDOM.png"
    local goto_log shot_log goto_rc shot_rc
    if ! curl -sf -m 3 "$url" >/dev/null 2>&1; then
      echo "- · $label: offline, skipped"
      return 0
    fi
    set +e
    goto_log=$("$BROWSE" goto "$url" 2>&1)
    goto_rc=$?
    if [ "$goto_rc" -ne 0 ]; then
      set -e
      echo "- ⚠ $label: goto failed ($(printf '%s' "$goto_log" | head -1))"
      return 0
    fi
    shot_log=$("$BROWSE" screenshot "$tmp_shot" 2>&1)
    shot_rc=$?
    set -e
    if [ "$shot_rc" -ne 0 ] || [ ! -f "$tmp_shot" ]; then
      echo "- ⚠ $label: screenshot failed ($(printf '%s' "$shot_log" | head -1))"
      rm -f "$tmp_shot"
      return 0
    fi
    mv "$tmp_shot" "$final_shot" 2>/dev/null || cp "$tmp_shot" "$final_shot"
    rm -f "$tmp_shot"
    local size
    size=$(stat -f%z "$final_shot" 2>/dev/null || stat -c%s "$final_shot" 2>/dev/null || echo "?")
    echo "- ✅ $label: $(basename "$final_shot") (${size}B)"
  }

  capture_surface "dashboard" "$DASHBOARD_URL"
  capture_surface "studio"    "${CLAWS_STUDIO_URL:-http://localhost:4319}"
  capture_surface "landing"   "${CLAWS_LANDING_URL:-http://localhost:3000}"

  # Set legacy SCREENSHOT var for downstream pruning logic
  SCREENSHOT="$AUDIT_DIR/dashboard-$TIMESTAMP.png"

  # 5. Console errors
  CONSOLE_OUTPUT=$("$BROWSE" console 2>/dev/null || echo "")
  if [ -n "$CONSOLE_OUTPUT" ]; then
    ERROR_COUNT=$(printf '%s\n' "$CONSOLE_OUTPUT" | grep -ic "error" 2>/dev/null | tr -d '[:space:]')
    WARN_COUNT=$(printf '%s\n' "$CONSOLE_OUTPUT" | grep -ic "warn" 2>/dev/null | tr -d '[:space:]')
    ERROR_COUNT=${ERROR_COUNT:-0}
    WARN_COUNT=${WARN_COUNT:-0}
    echo "- Console errors: $ERROR_COUNT"
    echo "- Console warnings: $WARN_COUNT"
    if [ "${ERROR_COUNT:-0}" -gt 0 ] 2>/dev/null; then
      echo
      echo "### Top errors"
      echo '```'
      printf '%s\n' "$CONSOLE_OUTPUT" | grep -i "error" | head -5
      echo '```'
    fi
  fi
  echo

  # 6. Verdict
  echo "## Verdict"
  echo "- Gateway: online"
  echo "- Dashboard: online"
  echo "- Visual: captured"
  echo
} > "$REPORT"

# Prune old audits (keep last 48 = 12 hours at 15min cadence)
ls -t "$AUDIT_DIR"/audit-*.md 2>/dev/null | tail -n +49 | xargs -I {} rm -f {} 2>/dev/null || true
ls -t "$AUDIT_DIR"/dashboard-*.png 2>/dev/null | tail -n +49 | xargs -I {} rm -f {} 2>/dev/null || true
ls -t "$AUDIT_DIR"/studio-*.png 2>/dev/null | tail -n +49 | xargs -I {} rm -f {} 2>/dev/null || true
ls -t "$AUDIT_DIR"/landing-*.png 2>/dev/null | tail -n +49 | xargs -I {} rm -f {} 2>/dev/null || true
ls -t "$AUDIT_DIR"/shot-*.png 2>/dev/null | xargs -I {} rm -f {} 2>/dev/null || true

# Update phase status pointer (so status scripts can see "last audit")
PHASE_STATUS="$CLAWS_HOME/phase-status.json"
cat > "$PHASE_STATUS.tmp" << EOF
{
  "lastAudit": "$TIMESTAMP",
  "lastAuditReport": "$REPORT",
  "gatewayHealthy": true,
  "dashboardHealthy": true
}
EOF
mv "$PHASE_STATUS.tmp" "$PHASE_STATUS"

echo "✔ QA audit complete: $REPORT"
